from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime

class UserProfile(BaseModel):
    """Represents the candidate's core profile and base CV."""
    full_name: str = Field(..., description="Full name of the candidate")
    email: str = Field(..., description="Email address")
    phone: Optional[str] = Field(None, description="Contact phone number")
    education: List[Dict[str, Any]] = Field(default_factory=list, description="Education history (degree, university, graduation year)")
    experience: List[Dict[str, Any]] = Field(default_factory=list, description="Work experience list (role, company, description, dates)")
    skills: List[str] = Field(default_factory=list, description="List of technical and soft skills")
    base_cv_text: str = Field(..., description="The raw, un-tailored base CV content")
    preferences: Dict[str, Any] = Field(default_factory=dict, description="Job preferences (locations, role types, industries)")

class JobListing(BaseModel):
    """Represents a job opportunity found during search."""
    job_id: str = Field(..., description="Unique job identifier")
    title: str = Field(..., description="Job title")
    company: str = Field(..., description="Company offering the job")
    description: str = Field(..., description="Full job description")
    location: str = Field(..., description="Job location")
    url: Optional[str] = Field(None, description="Link to the job listing")
    salary_range: Optional[str] = Field(None, description="Salary range, if specified")
    date_posted: Optional[str] = Field(None, description="Date the job was posted")
    requirements: List[str] = Field(default_factory=list, description="Extracted key requirements")

class TailoredCV(BaseModel):
    """Represents a CV tailored to a specific job description."""
    job_id: str = Field(..., description="ID of the job this CV is tailored for")
    tailored_cv_text: str = Field(..., description="The fully tailored CV text")
    alignment_score: float = Field(..., description="Percentage match or score indicating alignment (0.0 to 100.0)")
    key_changes: List[str] = Field(default_factory=list, description="Bullet points explaining the adjustments made")

class CoverLetter(BaseModel):
    """Represents a draft cover letter for a job application."""
    job_id: str = Field(..., description="ID of the job this cover letter is written for")
    letter_text: str = Field(..., description="The full text of the cover letter")
    tone: str = Field(..., description="The tone of the letter (e.g., professional, enthusiastic, academic)")
    key_highlights: List[str] = Field(default_factory=list, description="Main experiences highlighted in the letter")

class ApplicationState(BaseModel):
    """Represents the application tracking record in the local database."""
    application_id: Optional[str] = Field(None, description="Unique database ID, autogenerated if null")
    job_id: str = Field(..., description="ID of the job applied to")
    job_title: str = Field(..., description="Title of the job")
    company: str = Field(..., description="Company name")
    status: str = Field("applied", description="Status (applied, interviewing, rejected, offer)")
    timeline: List[Dict[str, Any]] = Field(default_factory=list, description="List of timeline events (e.g., date: event, notes: text)")
    last_updated: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of the last update")
    notes: Optional[str] = Field(None, description="General notes on this application")
